{{- if eq .Values.kubernetes.access "none" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-mooring.fullname" . }}
  labels:
    {{- include "agent-mooring.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
