apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-mooring.fullname" . }}
  labels:
    {{- include "agent-mooring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agent-mooring.selectorLabels" . | nindent 4 }}
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
